Resources:
  MyS3AccessPoint1:
    Type: AWS::S3::AccessPoint
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
